-- ============================================================
-- FacturLinEx2 - Control interno de rectificativas
-- Tienda: 0000
-- Puestos: A, B, C
-- Motor usado: MyISAM, siguiendo el estilo actual del proyecto.
-- ============================================================

CREATE TABLE IF NOT EXISTS rectifcab0000 (
  RC_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  RC_ORIG_TIPO CHAR(2) NOT NULL,
  RC_ORIG_FECHA DATE NOT NULL,
  RC_ORIG_HORA TIME NOT NULL,
  RC_ORIG_CAJA CHAR(1) NOT NULL,
  RC_ORIG_SERIE VARCHAR(10) NOT NULL,
  RC_ORIG_NUMERO INT NOT NULL,
  RC_RECT_TIPO CHAR(2) NOT NULL DEFAULT 'RE',
  RC_RECT_FECHA DATE NOT NULL,
  RC_RECT_HORA TIME NOT NULL,
  RC_RECT_CAJA CHAR(1) NOT NULL,
  RC_RECT_SERIE VARCHAR(10) NOT NULL,
  RC_RECT_NUMERO INT NOT NULL,
  RC_USUARIO VARCHAR(50) DEFAULT '',
  RC_MOTIVO VARCHAR(255) DEFAULT '',
  RC_HO20_RECT VARCHAR(500) DEFAULT '',
  RC_CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (RC_ID),
  UNIQUE KEY UK_RECTIFICATIVA_UNICA (RC_RECT_TIPO, RC_RECT_SERIE, RC_RECT_NUMERO),
  KEY IDX_ORIGINAL (RC_ORIG_TIPO, RC_ORIG_SERIE, RC_ORIG_NUMERO),
  KEY IDX_ORIGINAL_COMPLETA (RC_ORIG_TIPO, RC_ORIG_FECHA, RC_ORIG_HORA, RC_ORIG_CAJA, RC_ORIG_SERIE, RC_ORIG_NUMERO)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE IF NOT EXISTS rectiflin0000 (
  RL_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  RL_CAB_ID BIGINT UNSIGNED NOT NULL,
  RL_ORIG_TIPO CHAR(2) NOT NULL,
  RL_ORIG_FECHA DATE NOT NULL,
  RL_ORIG_HORA TIME NOT NULL,
  RL_ORIG_CAJA CHAR(1) NOT NULL,
  RL_ORIG_SERIE VARCHAR(10) NOT NULL,
  RL_ORIG_NUMERO INT NOT NULL,
  RL_ORIG_LINEA INT NOT NULL,
  RL_RECT_TIPO CHAR(2) NOT NULL DEFAULT 'RE',
  RL_RECT_FECHA DATE NOT NULL,
  RL_RECT_HORA TIME NOT NULL,
  RL_RECT_CAJA CHAR(1) NOT NULL,
  RL_RECT_SERIE VARCHAR(10) NOT NULL,
  RL_RECT_NUMERO INT NOT NULL,
  RL_RECT_LINEA INT NOT NULL,
  RL_COD_ARTICULO VARCHAR(30) DEFAULT '',
  RL_DESCRIPCION VARCHAR(120) DEFAULT '',
  RL_QTY_ORIGINAL DOUBLE NOT NULL DEFAULT 0,
  RL_QTY_RECTIFICADA DOUBLE NOT NULL DEFAULT 0,
  RL_PVP_ORIGINAL_CON_IVA DOUBLE NOT NULL DEFAULT 0,
  RL_TOTAL_ORIGINAL_CON_IVA DOUBLE NOT NULL DEFAULT 0,
  RL_TOTAL_RECTIFICADO_CON_IVA DOUBLE NOT NULL DEFAULT 0,
  RL_IVA DOUBLE NOT NULL DEFAULT 0,
  RL_DTO DOUBLE NOT NULL DEFAULT 0,
  RL_CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (RL_ID),
  UNIQUE KEY UK_LINEA_RECTIFICATIVA_UNICA (RL_RECT_TIPO, RL_RECT_SERIE, RL_RECT_NUMERO, RL_RECT_LINEA),
  KEY IDX_LINEA_ORIGINAL (RL_ORIG_TIPO, RL_ORIG_SERIE, RL_ORIG_NUMERO, RL_ORIG_LINEA),
  KEY IDX_LINEA_ORIGINAL_COMPLETA (RL_ORIG_TIPO, RL_ORIG_FECHA, RL_ORIG_HORA, RL_ORIG_CAJA, RL_ORIG_SERIE, RL_ORIG_NUMERO, RL_ORIG_LINEA),
  KEY IDX_CAB_ID (RL_CAB_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE IF NOT EXISTS ventasrectif0000A (
  VR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  VR_LINEA_VENTA INT NOT NULL,
  VR_ORIG_TIPO CHAR(2) NOT NULL,
  VR_ORIG_FECHA DATE NOT NULL,
  VR_ORIG_HORA TIME NOT NULL,
  VR_ORIG_CAJA CHAR(1) NOT NULL,
  VR_ORIG_SERIE VARCHAR(10) NOT NULL,
  VR_ORIG_NUMERO INT NOT NULL,
  VR_ORIG_LINEA INT NOT NULL,
  VR_QTY_ORIGINAL DOUBLE NOT NULL DEFAULT 0,
  VR_QTY_A_RECTIFICAR DOUBLE NOT NULL DEFAULT 0,
  VR_IMP_ORIGINAL_CON_IVA DOUBLE NOT NULL DEFAULT 0,
  VR_IMP_A_RECTIFICAR_CON_IVA DOUBLE NOT NULL DEFAULT 0,
  VR_CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (VR_ID),
  UNIQUE KEY UK_VR_LINEA (VR_LINEA_VENTA),
  KEY IDX_VR_ORIG_LINEA (VR_ORIG_TIPO, VR_ORIG_FECHA, VR_ORIG_HORA, VR_ORIG_CAJA, VR_ORIG_SERIE, VR_ORIG_NUMERO, VR_ORIG_LINEA)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE IF NOT EXISTS ventasrectif0000B LIKE ventasrectif0000A;
CREATE TABLE IF NOT EXISTS ventasrectif0000C LIKE ventasrectif0000A;

-- Campos caché/opcionales para visualización rápida.
-- Ejecutar solo si aún no existen.
-- ALTER TABLE hisopcc0000
--   ADD COLUMN HO21_TIENE_RECTIF CHAR(1) NOT NULL DEFAULT 'N',
--   ADD COLUMN HO22_RECT_COUNT INT NOT NULL DEFAULT 0,
--   ADD COLUMN HO23_RECT_SALDO DOUBLE NOT NULL DEFAULT 0;

-- ALTER TABLE hisopdd0000
--   ADD COLUMN HOD24_QTY_RECT_ACUM DOUBLE NOT NULL DEFAULT 0,
--   ADD COLUMN HOD25_IMP_RECT_ACUM DOUBLE NOT NULL DEFAULT 0,
--   ADD COLUMN HOD26_RECT_SALDO_QTY DOUBLE NOT NULL DEFAULT 0,
--   ADD COLUMN HOD27_RECT_SALDO_IMP DOUBLE NOT NULL DEFAULT 0;
