#DROP TABLE autofabri;
CREATE TABLE IF NOT EXISTS autofabri
	(
	AUT0 INT(4) NOT NULL DEFAULT 0,
	AUT1 CHAR(50),
	PRIMARY KEY kaut (AUT0),
        UNIQUE (AUT0),
	INDEX kaut (AUT0)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
