DROP TABLE IF EXISTS cambios;
CREATE TABLE IF NOT EXISTS cambios (
	CA0 VARCHAR(13) NOT NULL,
	CA1 VARCHAR(50),
	CA2 DOUBLE(10,2),
	PRIMARY KEY kca (CA0),
	UNIQUE (CA0),
	INDEX kca (CA0))
	ENGINE=InnoDB DEFAULT CHARSET=utf8;
