DROP TABLE familias0000;
CREATE TABLE familias0000
	(
	F0 INT(4) NOT NULL,
	F1 CHAR(50),
	F2 INT(4) NOT NULL DEFAULT 0,
	F3 DATE,
	F4 DATE,
	F5 BLOB,
	PRIMARY KEY kf (F0),
        UNIQUE (F0),
	INDEX kf (F0)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
