CREATE TABLE geconomica0000 ( 
	Id INTEGER  NOT NULL AUTO_INCREMENT, 
	Fecha DATE  NOT NULL, SaldoI DOUBLE(10,3)  NOT NULL DEFAULT 0, 
	Cambios DOUBLE(10,3)  NOT NULL DEFAULT 0, 
	RetiraF DOUBLE(10,3)  NOT NULL DEFAULT 0, 
	Observaciones BLOB, 
PRIMARY KEY Kld (Id), UNIQUE (Id), INDEX kld (Id)) ENGINE = InnoDB DEFAULT CHARSET=utf8;

