#DROP TABLE puntos;
CREATE TABLE puntos 
	(
  	P0 DATE  NOT NULL,
  	P1 TIME  NOT NULL,
  	P2 CHAR(2)  NOT NULL,
  	P3 CHAR(13)  NOT NULL,
  	P4 CHAR(13)  NOT NULL,
  	P5 CHAR(3)  NOT NULL,
  	P6 CHAR(13)  NOT NULL,
  	P7 CHAR(50)  NOT NULL,
  	P8 CHAR(2)  NOT NULL,
  	P9 CHAR(10)  NOT NULL,
  	P10 CHAR(10)  NOT NULL,
  	PRIMARY KEY (P0, P1, P2, P3, P4, P5, P6, P7)
	) ENGINE = InnoDB DEFAULT CHARSET=utf8;

