DROP TABLE rutas;
CREATE TABLE rutas0000 (
  RUT0 INT(7) NOT NULL DEFAULT 0,
  RUT1 VARCHAR(100),
  PRIMARY KEY krut (RUT0),
  UNIQUE (RUT0),
  INDEX krut (RUT0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
