#DROP TABLE seriesfactu;
CREATE TABLE seriesfactu
	(
	SF0 CHAR(3) NOT NULL,
	SF1 CHAR(50),
	SF2 INT(7) NOT NULL DEFAULT 0,
	SF3 INT(7) NOT NULL DEFAULT 0,
	SF4 INT(7) NOT NULL DEFAULT 0,
	SF5 CHAR(1) NOT NULL DEFAULT 'N',
	SF6 INT(7) NOT NULL DEFAULT 0,
	SF7 INT(7) NOT NULL DEFAULT 0,
	SF8 INT(7) NOT NULL DEFAULT 0,
	PRIMARY KEY ksf (SF0),
        UNIQUE (SF0),
	INDEX ksf (SF0)
	);
